### ISSUE TITLE
Ajouter le plugin `strapi-plugin-populate-deep`

### ISSUE THREAD

**Issue by PaulMorel** [ouvroir/cieco-strapi#5]
@emchateau La nature du REST API fait en sorte qu'il faut spécifier la hiérarchie des zone dynamiques pour y retirer leur contenu. Ça ne semble pas fonctionner avec les slider, car les zones sont imbriqués. Je ne sais pas si c'est un bug de Strapi ou un manquement de mon côté. 

Peu importe, il y a un plugin pour simplifier ces types d’interactions que je crois serait un bon ajout à la plateforme.

https://www.npmjs.com/package/strapi-plugin-populate-deep

Jette s'y un coup d’œil, dit-moi ce que t'en penses.

**Comment by emchateau** [comment]
Discussion le 24 février. 
- ne change pas le comportement par défaut
- ne semble pas créer trop de dépendances
Ok on va l’installer
